question_data = [
    {"type": "boolean", "difficulty": "medium", "category": "Science: Mathematics",
     "question": "Zero factorial is equal to zero. ", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "medium", "category": "General Knowledge",
     "question": "On average, Americans consume 100 pounds of what per second?", "correct_answer": "Chocolate",
     "incorrect_answers": ["Potatoes", "Donuts", "Cocaine"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Comics",
     "question": "In Calvin and Hobbes, what is the name of the principal at Calvin's school?",
     "correct_answer": "Mr. Spittle", "incorrect_answers": ["Mr. Boreman", "Mr. Spitling", "Mr. Moe"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Music",
     "question": "What is the name of Rivers Cuomo&#039;s wife?", "correct_answer": "Kyoko Ito",
     "incorrect_answers": ["Yoko Ono", "Kyary Pamyu Pamyu", "LiSA"]},
    {"type": "multiple", "difficulty": "hard", "category": "Science: Computers",
     "question": "What is the name given to layer 4 of the Open Systems Interconnection (ISO) model?",
     "correct_answer": "Transport", "incorrect_answers": ["Session", "Data link", "Network"]},
    {"type": "multiple", "difficulty": "medium", "category": "Mythology",
     "question": "What is the name of the first human being in Norse mythology?", "correct_answer": "Ask",
     "incorrect_answers": ["Asmund", "Ake", "Asger"]},
    {"type": "multiple", "difficulty": "easy", "category": "Science: Gadgets", "question": "What does GPS stand for?",
     "correct_answer": "Global Positioning System",
     "incorrect_answers": ["Global Personal System", "General Positioning System", "General Personal Satellite"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "What video game sparked controversy because of its hidden &quot;Hot Coffee&quot; minigame?",
     "correct_answer": "Grand Theft Auto: San Andreas",
     "incorrect_answers": ["Grand Theft Auto: Vice City", "Hitman: Blood Money", "Cooking Mama"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "In the Halo series, what fleet was Thel &#039;Vadam supreme commander of before being branded an Arbiter?",
     "correct_answer": "Fleet of Particular Justice",
     "incorrect_answers": ["Fleet of Sacred Consecration", "Fleet of Furious Redemption",
                           "Fleet of Righteous Vigilance"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Film",
     "question": "What film did James Cameron&#039;s Avatar dethrone as the highest-grossing film ever?",
     "correct_answer": "Titanic", "incorrect_answers": ["Star Wars", "Gone with the Wind", "Jaws"]}]
